{
 "title": "Database Exporter",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "table",
    "query": {
     "query": "label_values(pg_stat_user_tables_table_size_bytes{datname=\"soccer\"}, relname)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Tuples Operations per Table",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_stat_user_tables_n_tup_ins{datname=\"soccer\", relname=\"$table\"}\r\n+ pg_stat_user_tables_n_tup_upd{datname=\"soccer\", relname=\"$table\"}\r\n+ pg_stat_user_tables_n_tup_del{datname=\"soccer\", relname=\"$table\"}\r\n",
     "legendFormat": "{{relname}}"
    }
   ]
  },
  {
   "title": "Scrape Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "pg_exporter_last_scrape_duration_seconds\r\n",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Hot Tables",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "pg_stat_user_tables_n_tup_ins{datname=\"soccer\"} \r\n+ pg_stat_user_tables_n_tup_upd{datname=\"soccer\"} \r\n+ pg_stat_user_tables_n_tup_del{datname=\"soccer\"}\r\n",
     "legendFormat": "{{relname}}"
    }
   ]
  },
  {
   "title": "Active connections",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_stat_database_numbackends{datname=\"soccer\"}\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Temporary File Usage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_stat_database_temp_files{datname=\"soccer\"}\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Database Size",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_database_size_bytes{datname=\"soccer\"} / 1024 /1024\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sequential vs Index Scans",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_stat_user_tables_seq_scan{datname=\"soccer\"}",
     "legendFormat": "Seq Scan: {{relname}} ({{schemaname}})"
    },
    {
     "expr": "pg_stat_user_tables_idx_scan{datname=\"soccer\"}",
     "legendFormat": "Index Scan: {{relname}} ({{schemaname}})"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_cpu_seconds_total{instance=\"postgres-exporter:9187\", job=\"postgres-exporter\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Table Size",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_stat_user_tables_table_size_bytes{datname=\"soccer\"} / 1024 / 1024 / 1024\r\n",
     "legendFormat": "{{relname}} ({{schemaname}})"
    }
   ]
  },
  {
   "title": "Cache hit ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "rate(pg_stat_database_blks_hit{datname=\"soccer\"}[5m])\r\n/\r\n(rate(pg_stat_database_blks_hit{datname=\"soccer\"}[5m])\r\n + rate(pg_stat_database_blks_read{datname=\"soccer\"}[5m]))\r\n",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Tuples inserted",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "rate(pg_stat_database_tup_inserted{datname=\"soccer\"}[5m])\r\n",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}