{
 "title": "Node Exporter",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "device",
    "query": {
     "query": "label_values(node_disk_written_bytes_total, device)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime ",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds - node_boot_time_seconds",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Context Switches",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "label_replace(\r\n  rate(node_context_switches_total[5m]),\r\n  \"display_name\",\r\n  \"Context Switches\",\r\n  \"__name__\",\r\n  \".*\"\r\n)\r\n",
     "legendFormat": "{{display_name}}"
    }
   ]
  },
  {
   "title": "System Load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "label_replace(node_load1, \"display_name\", \"OS Node Load 1m\", \"__name__\", \"node_load1\")\r\n",
     "legendFormat": "{{display_name}}"
    }
   ]
  },
  {
   "title": "Network Out (MB/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "expr": "label_replace(\r\n  rate(node_network_transmit_bytes_total{device=\"eth0\"}[5m]) / 1024 / 1024,\r\n  \"display_name\",\r\n  \"Main Network Interface\",\r\n  \"device\",\r\n  \"eth0\"\r\n)\r\n",
     "legendFormat": "{{display_name}}"
    },
    {
     "expr": "label_replace(\r\n  rate(node_network_transmit_bytes_total{device=\"lo\"}[5m]) / 1024 / 1024,\r\n  \"display_name\",\r\n  \"Loopback Interface\",\r\n  \"device\",\r\n  \"lo\"\r\n)\r\n",
     "legendFormat": "{{display_name}}"
    }
   ]
  },
  {
   "title": "Network In ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total[5m]) / 1024 / 1024",
     "legendFormat": "{{device}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Disk Write ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "GBs" } },
   "targets": [
    {
     "expr": "rate(node_disk_written_bytes_total{device=~\"sdb|sdc|sdd|sde|sdf\"}[5m]) / 1024 / 1024 / 1024\r\n",
     "legendFormat": "{{display_name}}"
    },
    {
     "expr": "label_replace(\r\n  rate(node_disk_written_bytes_total{device=\"sda\"}[5m]) / 1024 / 1024 / 1024,\r\n  \"display_name\",\r\n  \"OS Disk\",\r\n  \"device\",\r\n  \"^sda$\"\r\n)\r\n",
     "legendFormat": "{{display_name}} {{device}}"
    }
   ]
  },
  {
   "title": "Disk Read ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "GBs" } },
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total[5m]) / 1073741824\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage ",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Free Disk Space ",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_filesystem_avail_bytes) / (1024*1024*1024)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage ",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}